import { useState, useEffect } from 'react';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

import Head from 'next/head';
import Header from '@/components/Header';
import Main from '@/components/MainPageNotLoggedIn/Main';
import Footer from '@/components/Footer/Footer';

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const typedLocale = locale as string;
  return {
    props: {
      ...(await serverSideTranslations(
        typedLocale,
        [
          'headerMenu',
          'mainPageNotLoggedIn',
          'footer',
          'registerPopup',
          'signInPopup'
        ],
        null,
        ['en', 'ru', 'id']
      )),
    },
  }
}

export default function Home() {
  const { i18n } = useTranslation();

  useEffect(() => { 
    const defaultLang = localStorage.getItem('language');
    if (defaultLang) {
      i18n.changeLanguage(defaultLang);
    }
  }, []);

  // ? переделать стейт на енам, где будет три значения - одно значение false для состояния закрытого попапа, и две строки - например, reg и signIn, на основании которых будет меняться лэйаут 
  const [isPopupOpen, setIsPopupOpen] = useState<boolean>(false);

  const handlePopupOpen = () => {
    setIsPopupOpen(true);
  }

  const handlePopupClose = () => {
    setIsPopupOpen(false);
  }

  const [isRegPopup, setIsRegPopup] = useState<boolean>(true);

  const openRegPopup = () => {
    setIsRegPopup(true);
  }

  const openSignInPopup = () => {
    setIsRegPopup(false);
  }

  return (
    <main className="bg-ocean-reef bg-cover bg-center flex flex-col justify-between min-h-screen w-full">
      <Head>
      <title>BaliGreenMap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <Header onPopupOpen={handlePopupOpen} openSignInPopup={openSignInPopup} />
      <Main
        isPopupOpen={isPopupOpen}
        onPopupOpen={handlePopupOpen}
        onPopupClose={handlePopupClose}
        isRegPopup={isRegPopup}
        openRegPopup={openRegPopup}
        openSignInPopup={openSignInPopup}
      />
      <Footer />
    </main>
  )
}