import { ReactElement } from "react";
import Head from "next/head";

const AppHead: React.FC = (): ReactElement => {
  return (
    <Head>
      <title>BaliGreenMap</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/images/svgs/white-logo.svg" />
  </Head>
  )
}

export default AppHead;