import Manatee from '../../public/images/backgrounds/manatee.png';
import { PostType } from './types';

export const posts: Array<PostType> = [
  {
    title: 'ololo1',
    date: '22.11.1991',
    id: 1,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo2',
    date: '',
    id: 2,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo3',
    date: '',
    id: 3,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo4',
    date: '',
    id: 4,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo5',
    date: '',
    id: 5,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo1',
    date: '22.11.1991',
    id: 1,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo2',
    date: '',
    id: 2,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo3',
    date: '',
    id: 3,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo4',
    date: '',
    id: 4,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
  {
    title: 'ololo5',
    date: '',
    id: 5,
    text: 'ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo ololoo loloolo loololoolol oololoololo ololoololoo loloololool oloololoolo loololoolol oololoololo ololoololo',
    photo: Manatee,
    photoUrl: Manatee.src,
  },
]