export const ecoTips: Array<string> = [
  'Use reusable bags for shopping to reduce plastic waste.',
  'Turn off lights and appliances when not in use to conserve energy.',
  'Walk, bike, or use public transportation instead of driving to reduce emissions.',
  'Plant a garden to grow your own fruits and vegetables, which reduces the need for transportation and packaging.',
  'Install energy-efficient LED light bulbs.',
  'Fix leaky faucets to conserve water.',
  'Use a reusable water bottle instead of disposable plastic bottles.',
  'Use eco-friendly cleaning products to reduce harmful chemicals in your home.',
  'Recycle paper, glass, and plastic to reduce waste.',
  'Compost kitchen scraps to create nutrient-rich soil for your garden.',
  'Use cloth napkins and towels instead of paper ones.',
  'Donate or sell unwanted items instead of throwing them away.',
  'Use solar-powered chargers for your devices.',
  'Choose products with minimal packaging to reduce waste.',
  'Shop at second-hand stores to extend the life of clothing and other items.',
  'Install a low-flow showerhead to save water.',
  'Unplug chargers and devices when not in use to conserve energy.',
  'Use a programmable thermostat to optimize heating and cooling.',
  'Collect rainwater for gardening and landscaping.',
  'Avoid single-use items like disposable cutlery and plates.',
  'Support eco-friendly businesses and products.',
  'Opt for e-billing to save paper.',
  'Choose energy-efficient appliances when upgrading.',
  'Hang clothes to dry instead of using a dryer.',
  'Use reusable containers for food storage and transport.',
  'Carpool with friends or coworkers',
  'Buy locally-produced goods to support local economies and reduce transportation emissions.',
  'Plant trees or support reforestation efforts to offset carbon emissions.',
  'Replace disposable batteries with rechargeable ones.',
  'Swap out plastic wrap for reusable beeswax wraps or silicone lids.',
  'Choose natural fibers like cotton, linen, or hemp for clothing and bedding.',
  'Reduce meat consumption to lower your carbon footprint.',
  'Practice upcycling to transform waste materials into new, useful items.',
  'Share and borrow items with friends and neighbors instead of purchasing new ones.',
  'Volunteer for local environmental initiatives, such as clean-ups or tree planting events.',
  'Opt for e-books or audiobooks instead of physical copies to save paper.',
  'Invest in solar panels for your home.',
  'Use cloth or reusable silicone bags for food storage.',
  'Replace your lawn with native plants to save water and support local ecosystems.',
  'Encourage your workplace to adopt sustainable practices.',
  'Learn about the environmental impact of your favorite products and make conscious choices.',
  'Turn off your computer at night to save energy.',
  'Say no to junk mail by opting out of unsolicited catalogs and advertisements.',
  'Choose products made from recycled materials.',
  'Practice the "5 Rs": Refuse, Reduce, Reuse, Repurpose, and Recycle.',
  'Install a water filter instead of buying bottled water.',
  'Use a reusable coffee cup for your daily caffeine fix.',
  'Maintain your car, bike, or other transportation to ensure energy efficiency.',
  'Choose slow fashion and high-quality, long-lasting items.',
  'Educate others about the importance of living a conscious and eco-sustainable life.'
];